### ISSUE TITLE
Improve errors

### ISSUE THREAD

**Issue by moodlezoup** [a16z/jolt#20]
Add more descriptive errors to `errors.rs`

**Comment by mw2000** [comment]
@moodlezoup was looking at contributing to this, but it looks like #47 and a few other fixes by @huitseeker should have solved this issue, let me know if there's still stuff to be done.

**Comment by moodlezoup** [comment]
I'm going to close for now –– there's definitely still lots of room for improvements but we'll create a more specific/descriptive issues
