### ISSUE TITLE
Add support for Zeromorph and/or HyperKZG commitments in addition to Hyrax

### ISSUE THREAD

**Issue by GUJustin** [a16z/jolt#208]
Zeromorph is described in this paper: https://eprint.iacr.org/2023/917. But it's very focused on hiding/zk, which is not an initial priority for Jolt. 

HyperKZG is described and implemented here: https://github.com/microsoft/Nova/blob/main/src/provider/hyperkzg.rs

Switching to these commitment schemes will reduce verifier costs to logarithmic and slightly speed up the prover too.

**Comment by Ethan-000** [comment]
ill give a try at porting hyperkzg based on https://github.com/a16z/jolt/pull/339 if nobody else is working on it

**Comment by moodlezoup** [comment]
That would be amazing!
