### ISSUE TITLE
RV32I M-Extension

### ISSUE THREAD

**Issue by GUJustin** [a16z/jolt#251]
More instructions: The Jolt codebase currently implements the RISC-V 32-bit Base Integer instruction set (RV32I), but the Jolt construction is highly flexible. Add support for the RISC-V “M”  extension for integer multiplication and division, as described in the [Jolt paper](https://eprint.iacr.org/2023/1217). Further, Jolt can trivially support the 64-bit variant RV64IM.

**Comment by mw2000** [comment]
@GUJustin @moodlezoup potentially interested in tackling this if an open issue, might need a few eyes on my PR drafts as I implement this 😄

**Comment by moodlezoup** [comment]
Hi @mw2000, feel free to give it a shot! My suggestion would be to start with just the instructions/subtables for the (32-bit) M extension (i.e. the stuff in `jolt-core/src/jolt/instruction` and `jolt-core/src/jolt/subtable`). The rest of the work shouldn't be too bad either, but will require some refactoring (as described in the Jolt paper, the M extension introduces the notion of "virtual instructions", which complicates things a bit)

**Comment by mw2000** [comment]
Sounds good! I'll make small atomic PRs for the instructions and pass them over for review.

More than happy to break this issue into smaller ones (and use this as the bucket) if it makes sense for tracking (assuming 1 issue = 1 PR)

**Comment by moodlezoup** [comment]
Sure, go for it. Thanks for taking this on!

**Comment by mw2000** [comment]
Hey guys, still on it. I should have something up in next couple days

**Comment by moodlezoup** [comment]
Great, let me know if you have any questions!

**Comment by mw2000** [comment]
Hey @moodlezoup Was implementing the non-virtual multiplication instructions, MUL, MULU and MULHU. I was able to get the first two running just fine, but running into some trouble with MULHU.

With this context, i wanted to understand what exactly a subtable is and if you could add more color to the jolt_instruction_test! Macro

**Comment by Ethan-000** [comment]
hi. are people working on rest of the instructions such as div and rem?

**Comment by mw2000** [comment]
@Ethan-000  Feel free to dm me on TG, my handle is that_one_nerdy

Right now we've been coordinating over DM, but happy to create a group or something similar
