### ISSUE TITLE
ReadWriteMemory::get_polys_r1cs by reference

### ISSUE THREAD

**Issue by sragss** [a16z/jolt#295]
`ReadWriteMemory::get_polys_r1cs()` is extremely slow ([here](https://github.com/a16z/jolt/blob/main/jolt-core/src/jolt/vm/read_write_memory.rs#L761)) because it clones all of the underlying not once but twice. On a ~16M cycle count trace on a 64 core machine it takes 2% of end-to-end time.

First: remove the double clones from `self.v_read` and `self.v_write_rd`. Double clones come from a clone in `DensePolynomial::evals()` then another in `.flat_map(...).collect()`. 

Second: refactor `get_polys_r1cs()` to return lifetimed references to the underlying vectors via `DensePolynomial::evals_ref()` rather than cloning / reallocating at all.

It may be helpful to review the [tracing strategy](https://jolt.a16zcrypto.com/dev/tools.html#tracing) for performance testing.

**Comment by MatteoMer** [comment]
hey! Would be happy to take this!

**Comment by sragss** [comment]
Great! Feel free to ask questions here.

**Comment by moodlezoup** [comment]
Closed by #307
