### ISSUE TITLE
Add wasm target

### ISSUE THREAD

**Issue by Levike34** [a16z/jolt#314]
Would be very useful if jolt could be compiled to a WASM executable

**Comment by sebasti810** [comment]
I’ve started to look into this, but want to get some clarification before I spend too much time on the wrong path - should we also have first class support for the prover, or is the verifier sufficient ([as done here](https://github.com/a16z/jolt/issues/209#issuecomment-2055581251))? I’m assuming the big selling point here would be embedding verifiers into webapps, but does it make sense to make the prover wasm compatible as well?

One way we could do this is by introducing a new jolt command, e.g. `jolt create-wasm …`, which could take over the process of creating the required components and then generating the WASM-compatible binaries… should I continue down this road?

**Comment by larron** [comment]
@sebasti810 Support for in browser verifiable compute would be awesome, IE: [Noir](https://medium.com/aztec-protocol/announcing-noirjs-privacy-preserving-zk-applications-in-your-browser-d7d78692f15a)
