### ISSUE TITLE
Wiki: Intro to RISC-V

### ISSUE THREAD

**Issue by sragss** [a16z/jolt#320]
Add a brief intro RISC-V to the wiki. Quick and dirty. Explain RV32I, LLVM. Link to datasheet.

The wiki autodeploys from the `mdbook` layout in `/book`.

**Comment by 4rgon4ut** [comment]
I'd like to take that

**Comment by emlazzarin** [comment]
Go for it. Do you have an expected timeline?

**Comment by 4rgon4ut** [comment]
> Go for it. Do you have an expected timeline?

Thanks, I will have enough capacity during this week
