### ISSUE TITLE
Wiki: Explanation of RAM (Read Write memory) Timestamp Rangecheck

### ISSUE THREAD

**Issue by sragss** [a16z/jolt#341]
[Spice](https://eprint.iacr.org/2018/907.pdf) describes this in Figure 2. The goal is to avoid reordering attacks. We need to guarantee that the prover's insertions happen in the correct order. 

Current implementation: Prove`read timestamps <= global_timestamp` for all insertions in `2^n`.
- Rangecheck `0 <= every read timestamp <= 2^n`
- Rangecheck`0 <= global_timestamp - read_timestamp <= 2^n`

**Comment by moodlezoup** [comment]
https://jolt.a16zcrypto.com/how/read_write_memory.html#timestamp-range-check
