### ISSUE TITLE
Sumcheck Optimizations

### ISSUE THREAD

**Issue by sragss** [a16z/jolt#348]
Angus Gruen mentions some tricks [here](https://eprint.iacr.org/2024/108.pdf) – notably in section 3.2

**Comment by tahsintunan** [comment]
Will take a swing at it

**Comment by mw2000** [comment]
hey @tahsintunan are you still working on this? would love to potentially take this on

**Comment by tahsintunan** [comment]
Hey @mw2000, I’m still working on this but got bogged down by some stuff. I’ll let you know if I need to pass it on.

**Comment by mw2000** [comment]
sounds good!

**Comment by mw2000** [comment]
@moodlezoup claiming this for now!
