### ISSUE TITLE
Refactor `EqPolynomial::evals`

### ISSUE THREAD

**Issue by moodlezoup** [a16z/jolt#351]
https://github.com/a16z/jolt/blob/main/jolt-core/src/poly/eq_poly.rs

Currently the function signature is `pub fn evals(&self) -> Vec<F>`
If we change this to `pub fn evals(r: &[F]) -> Vec<F>`, we should be able to avoid some unnecessary cloning throughout the codebase.

**Comment by SuccinctPaul** [comment]
hi, @moodlezoup , I've submitted a pr. Please review

**Comment by moodlezoup** [comment]
#355
