### ISSUE TITLE
How to specify private inputs?

### ISSUE THREAD

**Issue by ix42** [a16z/jolt#362]
Is there a way to specify private inputs for the functions in guest such that commitments are passed to the verifier instead of the raw values? All inputs are in the proof's serialized program_io.

**Comment by sragss** [comment]
Hi @ix42 thanks for trying out Jolt. Unfortunately we do not support Zero-knowledge today. [Here are some details](https://jolt.a16zcrypto.com/future/zk.html) on what it would take to get there.
