### ISSUE TITLE
A mistake in Lasso explanation

### ISSUE THREAD

**Issue by doutv** [a16z/jolt#366]
Great Video talking about Lasso! https://youtu.be/iDcXj9Vx3zY?feature=shared

However, I found a mistake in the excalidraw graph.
The last element of lookup result `a` should be 7
![image](https://github.com/a16z/jolt/assets/20609724/f61283aa-42a3-43d4-ad3b-cc6d672c76b8)

Files: https://github.com/a16z/jolt/blob/master/imgs/

Btw, why you remove this Lasso image from the main branch? I think it is great.
@moodlezoup

**Comment by moodlezoup** [comment]
Thanks for catching this! Will fix and reupload. I removed it because I wanted to create an updated version of the diagram for Jolt, but that's taken longer than expected 😓
