### ISSUE TITLE
Bug report: Memory/Instruction decoding

### ISSUE THREAD

**Issue by benoitrazet** [a16z/jolt#391]
We are encountering a bug while developing a matrix multiplication example, which causes the program to crash when the size of the square matrix is set to be greater than or equal to 19. This issue appears to be related to the program encountering a compressed RISC-V instruction.

Steps to reproduce the bug:

Clone the repository and checkout the relevant branch
```
git clone https://github.com/benoitrazet/jolt.git
cd jolt
git checkout bug/matmul-compressed-instr
```

Run the matrix multiplication exampke:
```
cargo run -p matmul
```

Change the value of `N` [here](https://github.com/benoitrazet/jolt/blob/bug/matmul-compressed-instr/examples/matmul/guest/src/lib.rs#L4) to toggle the bug.

The expected behavior is that it should run successfully without any crash.

The actual behavior is that the program crashes when the matrix size `N` is set to 19 or greater.

Thanks to @jprider63 for helping with the initial troubleshooting of this issue.

**Comment by moodlezoup** [comment]
Try increasing the stack size (`#[jolt::provable(stack_size = 100000)]`)

Created an [issue](https://github.com/a16z/jolt/issues/395) for more descriptive errors here
