### ISSUE TITLE
Better errors for insufficient stack or memory size

### ISSUE THREAD

**Issue by moodlezoup** [a16z/jolt#395]
https://jolt.a16zcrypto.com/usage/troubleshooting.html#insufficient-memory-or-stack-size

Currently, the tracer will error out with nondescript errors like `Unknown memory mapping 7FFFFE04.`

The tracer should detect when we have exhausted the stack and/or heap, and throw a descriptive error if so

**Comment by ameya-deshmukh** [comment]
Hey! Can I take this up?

**Comment by moodlezoup** [comment]
Yeah go for it!

**Comment by moodlezoup** [comment]
@ameya-deshmukh Any update here?

**Comment by ameya-deshmukh** [comment]
Hey @moodlezoup! Sorry, couldn't find time to work on this. Can I grind this out over the weekend and give you an update by early Monday ET?

**Comment by moodlezoup** [comment]
Yeah that'd be great! Lmk if you need any pointers

**Comment by 4rgon4ut** [comment]
@ameya-deshmukh @moodlezoup I would like to have a try if you fine with that

**Comment by ameya-deshmukh** [comment]
Hey @4rgon4ut sure! I didn't get the time to work on this issue, all yours to take

**Comment by 4rgon4ut** [comment]
@moodlezoup I have two questions:

1. Would you like it to be panics with specified messages (based on the case) or new trap type [here](https://github.com/a16z/jolt/blob/main/tracer/src/emulator/cpu.rs#L110)
2. Does `tracer/src/emulator/cpu.rs` is the right place to add related tests?

**Comment by moodlezoup** [comment]
> @moodlezoup I have two questions:
> 
> 1. Would you like it to be panics with specified messages (based on the case) or new trap type [here](https://github.com/a16z/jolt/blob/main/tracer/src/emulator/cpu.rs#L110)
> 2. Does `tracer/src/emulator/cpu.rs` is the right place to add related tests?

Thanks for taking this! 
1. just a better panic message is fine
2. I think perhaps `tracer/src/emulator/mmu.rs` may be a better place for tests

**Comment by moodlezoup** [comment]
> @moodlezoup does stack grows downwards, from higher stack addr down to the `DRAM_BASE` ? [ref](https://github.com/a16z/jolt/blob/main/tracer/src/emulator/mmu.rs#L3)
> 
> ```rust
> /// DRAM base address. Offset from this base address
> /// is the address in main memory.
> pub const DRAM_BASE: u64 = 0x80000000;
> ```

Yes, I believe so
