### ISSUE TITLE
getrandom - target is not supported

### ISSUE THREAD

**Issue by ArielElb** [a16z/jolt#399]
![image](https://github.com/a16z/jolt/assets/94087682/51203861-e497-4af9-b14c-7d285ded1a76)

Getting the error above when trying to use rand in host.

Im running on ubuntu on wsl.

any ideas? 

ty !

**Comment by sragss** [comment]
It looks like you're trying to use randomness within the *guest*, not the *host*. The guest gets compiled to RV32I to run within a virtual machine. As a result it does not have access to system entropy as there's no concept of system IO within the zkVM.
