### ISSUE TITLE
Open-source CPU targets

### ISSUE THREAD

**Issue by taqtiqa-mark** [a16z/jolt#446]
Are any of the following open-source CPUs targets for Jolt?

Specifically, should I ever expect that Jolt will run on, say, the Berkeley/SiFive Rocket [rv32ima](https://github.com/chipsalliance/rocket-tools/blob/master/build-rv32ima.sh), etc

- [ ] Berkeley/SiFive Rocket - https://github.com/chipsalliance/rocket-chip
- [ ] Bluespec Flute - https://github.com/bluespec/Flute
- [ ] OpenHardware Group CVA6 - https://github.com/openhwgroup/cva6.git (a.k.a. ETH Zurich Ariane)
- [ ] PicoRV32 - https://github.com/YosysHQ/picorv32/tree/main
  - [RV32im instructions](https://github.com/YosysHQ/picorv32/tree/main#building-a-pure-rv32i-toolchain)

**Comment by moodlezoup** [comment]
While we don't have any concrete plans to support those specific targets, compiling Jolt to RISC-V may be useful as a step toward self-recursion (proving the verification of a Jolt proof using Jolt). This is not a priority right now, as we are currently focused on other paths toward recursion
