### ISSUE TITLE
Proof almost 20% slower since Hyrax changed to HyperKZG

### ISSUE THREAD

**Issue by vaqxai** [a16z/jolt#459]
Commit https://github.com/a16z/jolt/commit/160c7f4f44b90247bda73bef3eecfa5c9b2ee267 introduces changes, such as replacing `HyraxScheme` with `HyperKZG` in `jolt_core::jolt::vm::rv32i_vm`. That change makes my proof slow down from `12.3s` to `14.6s`. This is a considerable slowdown.

Why was this change introduced? Is it sill possible to use `HyraxScheme` for proving in the newest version, or use another way of speeding the process up? I don't like having to keep an outdated version of Jolt to maintain good proving times.

I am going to conduct thorough examination to find out exactly which part of the process became slower, and post results so perhaps you guys can also benefit from this and hopefully return to the previous (or better) speed.

**Comment by vaqxai** [comment]
Thanks for the clarification. Is there an ETA for these optimizations?

**Comment by moodlezoup** [comment]
You can expect some to land within the next month

**Comment by vaqxai** [comment]
Okay, if you have any leaders/open PRs for this, I'd be glad to help out bring this to reality :)
