### ISSUE TITLE
Divide-by-zero and division overflow handling

### ISSUE THREAD

**Issue by randomsleep** [a16z/jolt#498]
According to the RISC-V spec, divide-by-zero and division overflow won't raise exception. Instead, it will return specific values.

![image](https://github.com/user-attachments/assets/3b9d2d41-cdee-4bae-8773-355e6b4e816a)

In Jolt `DIV`, `DIVU`, `REM`, and `REMU` instruction this is not handled. There is `AssertValidDiv0Instruction` but it seems it is not used.

**Comment by randomsleep** [comment]
@moodlezoup Oh thanks! The code already handled that. The Jolt paper didn't mention these `AssertValidDiv0Instruction` instruction in `DIV`.

The `sequence_output` in `divu` and `remu` should be updated according to that?
https://github.com/a16z/jolt/blob/0220448cc8d515bbbaf2b9814ef02fd41d5d5261/jolt-core/src/jolt/instruction/divu.rs#L230-L232

**Comment by moodlezoup** [comment]
Ah yes, nice catch. That method's only used in tests so not super urgent but will make a note to fix!
