### ISSUE TITLE
Multiple Dense PCS

### ISSUE THREAD

**Issue by sragss** [a16z/jolt#8]
Surge uses the dense multilinear polynomial commitment scheme from [microsoft/Spartan](https://github.com/microsoft/Spartan). 

We can swap this PCS with any other dense multilinear PCS for different performance characteristics. There are not many other dense **multilinear** PCS written in Rust, but it's worth generalizing the interface.

**Comment by upalchowdhury** [comment]
@sragss are you thinking of using coefficients ? i was planning something like this 
https://github.com/upalchowdhury/LassoPCS/blob/master/src/poly/diffPoly.rs

**Comment by moodlezoup** [comment]
@upalchowdhury The polynomial commitment schemes we have in mind are multilinear variants of [KZG](https://www.iacr.org/archive/asiacrypt2010/6477178/6477178.pdf) ([PST](https://eprint.iacr.org/2011/587.pdf), [Zeromorph](https://eprint.iacr.org/2023/917), etc.), [Dory](https://eprint.iacr.org/2020/1274), [Ligero](https://eprint.iacr.org/2022/1608), [Brakedown](https://eprint.iacr.org/2021/1043)

**Comment by wyattbenno777** [comment]
What about Sona? @moodlezoup 

https://people.cs.georgetown.edu/jthaler/Lasso-paper.pdf
pg.15.

**Comment by sragss** [comment]
This is now tracked in newer issues. #249 #212
